# Generated by Django 4.2.11 on 2024-05-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('fdate', models.DateField()),
                ('ffare', models.FloatField()),
                ('fstart', models.CharField(max_length=30)),
                ('fend', models.CharField(max_length=30)),
            ],
        ),
    ]
